use super::token;

machine!(
    #[derive(Debug, PartialEq, Eq)]
    enum StateMachine {
        Data,
        RcData,
        RawText,
        ScriptData,
        PlainText,
        TagOpen,
        EndTagOpen,
        TagName{ pub(crate) token: token::Token },
        RcDataLessThanSign,
        RcDataEndTagOpen,
        RcDataEndTagName{ pub(crate) token: token::Token, pub(crate) tmp: String},
        RawTextLessThanSign,
        RawTextEndTagOpen,
        RawTextEndTagName,
        ScriptDataLessThanSign,
        ScriptDataEndTagOpen,
        ScriptDataEndTagName,
        ScriptDataEscapeStart,
        ScriptDataEscapeStartDash,
        ScriptDataEscaped,
        ScriptDataEscapedDash,
        ScriptDataEscapedDashDash,
        ScriptDataEscapedLessThanSign,
        ScriptDataEscapedEndTagOpen,
        ScriptDataEscapedEndTagName,
        ScriptDataDoubleEscapeStart,
        ScriptDataDoubleEscaped,
        ScriptDataDoubleEscapedDash,
        ScriptDataDoubleEscapedDashDash,
        ScriptDataDoubleEscapedLessThanSign,
        ScriptDataDoubleEscapeEnd,
        BeforeAttributeName{ pub(crate) token: token::Token },
        AttributeName{ pub(crate) token: token::Token },
        AfterAttributeName{ pub(crate) token: token::Token },
        BeforeAttributeValue{ pub(crate) token: token::Token },
        AttributeValueDoubleQuoted{ pub(crate) token: token::Token },
        AttributeValueSingleQuoted{ pub(crate) token: token::Token },
        AttributeValueUnquoted{ pub(crate) token: token::Token },
        AfterAttributeValueQuoted{ pub(crate) token: token::Token },
        SelfClosingStartTag{ pub(crate) token: token::Token },
        BogusComment{ pub(crate) token: token::Token },
        MarkupDeclarationOpen,
        CommentStart{ pub(crate) token: token::Token },
        CommentStartDash{ pub(crate) token: token::Token },
        Comment{ pub(crate) token: token::Token },
        CommentLessThanSign{ pub(crate) token: token::Token },
        CommentLessThanSignBang,
        CommentLessThanSignBangDash,
        CommentLessThanSignBangDashDash,
        CommentEndDash{ pub(crate) token: token::Token },
        CommentEnd{ pub(crate) token: token::Token },
        CommentEndBang{ pub(crate) token: token::Token },
        Doctype,
        BeforeDoctypeName,
        DoctypeName{ pub(crate) token: token::Token },
        AfterDoctypeName,
        AfterDoctypePublicKeyword,
        BeforeDoctypePublicIdentifier,
        DoctypePublicIdentifierDoubleQuoted,
        DoctypePublicIdentifierSingleQuoted,
        AfterDoctypePublicIdentifier,
        BetweenDoctypePublicAndSystemIdentifiers,
        AfterDoctypeSystemKeyword,
        BeforeDoctypeSystemIdentifier,
        DoctypeSystemIdentifierDoubleQuoted,
        DoctypeSystemIdentifierSingleQuoted,
        AfterDoctypeSystemIdentifier,
        BogusDoctype,
        CdataSection,
        CdataSectionBracket,
        CdataSectionEnd,
        CharacterReference { pub(crate) return_state: Box<StateMachine> },
        NamedCharacterReference,
        AmbiguousAmpersand,
        NumericCharacterReference,
        HexadecimalCharacterReferenceStart,
        DecimalCharacterReferenceStart,
        HexadecimalCharacterReference,
        DecimalCharacterReference,
        NumericCharacterReferenceEnd,

        Term
    }
);
